services:
  nextjs:
    image: node:18-alpine
    container_name: timer.ayushchugh.com
    working_dir: /app
    ports:
      - "3002:3000"
    expose:
      - "3000"
    command: "npm start"
    environment:
      NODE_ENV: production
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
